# yaml-language-server: $schema=./mapping_tool/config_schema.json
# Docs: ./README.md

### This is an example of a configuration file to be used for running the IMAP Mapping Tool

## Specification of the time periods to be used for map creation. Either a canonical map period or a list of custom time ranges can be specified, but not both.
# For the canonical_map_period, all properties below are required. Example of a canonical map period definition:
canonical_map_period:
  year: 2025            # The year corresponding to the first map
  quarter: 2            # The quarter corresponding to the first map
  map_period: 3         # The map period for each map in months (e.g. 3, 6, 12)
  number_of_maps: 1     # The number of maps to be calculated for the output CDF file

# Example of a list of custom date ranges definition:
#time_ranges:
#  - start: 2025-06-15 # The start date of the first map period
#    end: 2025-08-01 # The end date of the first map period
#  - start: 2025-04-15 # The start date of a second map
#    end: 2025-05-01 # The end date of a second map

## The instrument to be used to generate the map.
# Valid options are: "Hi 45", "Hi 90", "Hi combined", "Ultra 45", "Ultra 90", "Ultra combined", "Lo"
instrument: Hi 90

## The spin phase to be used to generate the map.
# valid options are: "ram", "anti-ram", "full spin"
spin_phase: ram

## The reference frame to be used for the map projection.
# valid options are: "spacecraft", "heliospheric"
reference_frame: spacecraft

## Boolean value indicating whether the map should be survival-probability corrected
survival_corrected: true

## The SPICE frame to be used for the map projection.
# Some frames (e.g. "hae") are defined by the mission and can be used without supplying a custom spice kernel.
spice_frame_name: hae

## The pixelation scheme to be used for map generation.
# Valid options are "square" or "healpix"
pixelation_scheme: square

## The pixel parameter to be used for map generation. This defines the degree resolution for square maps, and the nside for HEALPix maps
# Valid options are 2, 4, and 6 for square maps, and 16, 32, 64, 128, 256, and 512 for HEALPix maps
pixel_parameter: 2

## The primary map data type
# Valid parameters are "ENA Intensity" or "Spectral Index"
map_data_type: ENA Intensity

## The species used to create the map. Optional property, which only applies to IMAP-Lo maps.
# Valid parameters are "h" or "o"
lo_species: h

## Optional text suffix to be added to the map data type in the descriptor of the output file.
quantity_suffix: suffix

## Optional path to a SPICE kernel file to be included in map generation. Used in conjunction with the "spice_frame_name" to allow for custom frame definitions.
#kernel_path: ./spice_kernel.tf