#canonical_map_period:
#  year: 2025
#  quarter: 2
#  map_period: 3
#  number_of_maps: 1

# Should these just be date strings rather than date times? e.g. 20250101 or 2025-01-01
time_ranges:
  - start: 2025-04-15T00:00:00.1234+04:00
    end: 2025-05-01T00:00:00.1234+04:00
instrument: Hi 90

spin_phase: ram
reference_frame: spacecraft
survival_corrected: true
spice_frame_name: IMAP_HAE
pixelation_scheme: square
pixel_parameter: 2
map_data_type: ENA Intensity
lo_species: h
quantity_suffix: suffix
kernel_path: "./spice_kernel.tf"