canonical_map_period:
  year: 2025
  quarter: 3
  map_period: 3
  number_of_maps: 1

instrument: Ultra 90

spin_phase: Full spin
reference_frame: spacecraft
survival_corrected: false
spice_frame_name: IMAP_GCS
pixelation_scheme: square
pixel_parameter: 4
map_data_type: ENA Intensity
lo_species: h
quantity_suffix: SUFFIX
kernel_path: "./imap_science_100.tf"