canonical_map_period:
  year: 2025
  quarter: 2
  map_period: 6
  number_of_maps: 1

instruments:
  - Hi 90

spin_phase: ram
reference_frame: spacecraft
survival_corrected: false
spice_frame_name: IMAP_GCS
pixelation_scheme: square
pixel_parameter: 4
map_data_type: ENA Intensity
lo_species: h
quantity_suffix: GCS_MAP